# ------- Files needed to prepare runs -------------
[run_parameters]
# future local run config ini values
#catchment = cat-2410534
#catchment = cat-2420544
#catchment = cat-2420542
catchment = cat-2420532

#out_root_folder = data/output
out_root_folder = lisflood-output